version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - 8002:8002
  
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - 8000:8000